version: '3'

services:
  app:
    build: ./
    image: mean
    ports:
      - 80:4040
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: ubu
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: pa$$

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: ubu
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: pa$$
